import { StyleSheet, Dimensions } from "react-native";
const { height } = Dimensions.get("window");
const isSmallScreen = height < 700;

export const styles = StyleSheet.create({
  gradient: { flex: 1, overflow: "hidden" },
  scrollContent: { flexGrow: 1, paddingHorizontal: 20, justifyContent: "center", overflow: "hidden" },
  header: { alignItems: "center", marginBottom: isSmallScreen ? 16 : 28 },
  logoWrapper: {
    position: "relative",
    marginBottom: isSmallScreen ? 8 : 12,
    width: isSmallScreen ? 80 : 100,
    height: isSmallScreen ? 80 : 100,
  },
  logoContainer: {
    width: isSmallScreen ? 80 : 100,
    height: isSmallScreen ? 80 : 100,
    borderRadius: isSmallScreen ? 40 : 50,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    overflow: "hidden",
  },
  logoImage: { width: isSmallScreen ? 90 : 110, height: isSmallScreen ? 90 : 110, marginLeft: 5 },
  sparkBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    backgroundColor: "#f59e0b",
    borderRadius: 10,
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  appName: { fontSize: isSmallScreen ? 24 : 28, fontWeight: "800", color: "#ffffff", letterSpacing: 1 },
  taglineWrapper: { marginTop: isSmallScreen ? 4 : 6 },
  tagline: { fontSize: isSmallScreen ? 12 : 13, color: "rgba(255,255,255,0.85)", textAlign: "center" },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  cardTopBar: { height: 4 },
  tabContainer: {
    flexDirection: "row",
    margin: isSmallScreen ? 14 : 20,
    marginBottom: 0,
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    padding: 4,
  },
  tab: { flex: 1, paddingVertical: isSmallScreen ? 8 : 10, alignItems: "center", borderRadius: 10 },
  tabActive: { backgroundColor: "#ffffff", shadowColor: "#000", shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  tabText: { fontSize: 14, fontWeight: "600" },
  tabTextActive: { color: "#1e3a8a" },
  tabTextInactive: { color: "#94a3b8" },
  formTitle: { fontSize: isSmallScreen ? 18 : 20, fontWeight: "700", color: "#1e293b", marginTop: isSmallScreen ? 14 : 20, marginHorizontal: 20, textAlign: "center" },
  formSubtitle: { fontSize: 13, color: "#64748b", marginHorizontal: 20, marginBottom: isSmallScreen ? 10 : 16, marginTop: 4 },
  fieldContainer: { marginHorizontal: 20, marginBottom: isSmallScreen ? 10 : 14 },
  label: { fontSize: 13, fontWeight: "600", marginBottom: isSmallScreen ? 4 : 6 },
  inputWrapper: { flexDirection: "row", alignItems: "center", borderWidth: 1.5, borderRadius: 12, height: isSmallScreen ? 44 : 50 },
  inputIcon: { marginLeft: 14 },
  input: { flex: 1, fontSize: 15, paddingLeft: 10 },
  rightIconBtn: { position: "absolute", right: 14 },
  rememberRow: { alignItems: "flex-end", marginHorizontal: 20, marginBottom: 8, marginTop: -4 },
  forgotText: { fontSize: 13, fontWeight: "500" },
  submitButton: { marginHorizontal: 20, marginVertical: isSmallScreen ? 14 : 20, borderRadius: 14, overflow: "hidden" },
  submitGradient: { paddingVertical: isSmallScreen ? 12 : 15, alignItems: "center", justifyContent: "center" },
  submitContent: { flexDirection: "row", alignItems: "center", gap: 8 },
  submitText: { color: "#ffffff", fontSize: 16, fontWeight: "700" },
  versionRow: { alignItems: "center", marginBottom: 20, marginTop: 4, paddingHorizontal: 20, gap: 8 },
  divider: { height: 1, backgroundColor: "#e2e8f0", width: "100%" },
  versionText: { fontSize: 11, color: "#94a3b8", textAlign: "center" },
});